# Generated by Django 6.0.6 on 2026-07-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('MOMO', 'Mobile Money'), ('CASH', 'Cash on Delivery')], default='MOMO', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
