# Generated by Django 6.0.6 on 2026-07-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_payment_method_order_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Paste a direct Cloudinary image URL here. Upload your image at cloudinary.com → Assets → Upload, then right-click the image → Copy URL.', max_length=500),
        ),
    ]
