"""
Django settings for perfume_store project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file for local development.
# Using load_dotenv() without a path argument automatically searches
# upward from the current working directory — more reliable on Windows.
try:
    from dotenv import load_dotenv
    load_dotenv(override=True)
    # Fallback: also try the explicit path in case cwd differs
    _env_path = BASE_DIR / '.env'
    if _env_path.exists():
        load_dotenv(dotenv_path=str(_env_path), override=True)
except ImportError:
    pass  # python-dotenv not installed — rely on real env vars


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECRET_KEY: read from environment on production (Render auto-generates
# a secure one via render.yaml's generateValue: true). Falls back to the
# insecure development key locally — never expose the production value.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-gchqkt)0*)ymhq3bz-%b7ad^2kaae_00#!eu4f3oq=nuo#^qpu'
)

# DEBUG: False on Render (set via render.yaml), True locally by default.
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# ALLOWED_HOSTS: locally empty (Django allows all in debug mode).
# On Render, the ALLOWED_HOSTS env var is set to ".onrender.com" which
# Django interprets as a wildcard for all *.onrender.com subdomains.
# If you add a custom domain later, append it here e.g. ".aromallure.com".
_raw_hosts = os.environ.get('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _raw_hosts.split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    'shop',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # must be directly after SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'perfume_store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.store_name',
                'shop.context_processors.cart_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'perfume_store.wsgi.application'


# Database
# Uses dj-database-url to read a DATABASE_URL environment variable.
# On Render (and most hosting platforms), DATABASE_URL is injected
# automatically when you attach a PostgreSQL database to the service.
# Locally, if DATABASE_URL is not set, it falls back to SQLite so
# you don't need PostgreSQL installed on your own machine just to
# run the dev server.
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# STATIC_ROOT is where collectstatic gathers all static files for production.
# WhiteNoise serves them from here (with compression + long cache headers).
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ── Media files ──────────────────────────────────────────────────────────────
# Render's filesystem is ephemeral — any uploaded files (product images)
# are wiped on every redeploy. Cloudinary stores them permanently in the
# cloud. The free tier (25GB storage, 25GB/month bandwidth) is more than
# enough for a growing perfume store.
# Set CLOUDINARY_URL in your .env locally and in Render's env vars.
CLOUDINARY_URL = os.environ.get('CLOUDINARY_URL', '')
if CLOUDINARY_URL:
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    CLOUDINARY_STORAGE = {'CLOUDINARY_URL': CLOUDINARY_URL}
else:
    # Local development fallback — images stored in /media/ folder
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ── Logging ───────────────────────────────────────────────────────────────────
# Errors in production are silently swallowed without this.
# Render captures stdout/stderr — you can view logs in the Render dashboard.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'shop': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auth redirects
LOGIN_REDIRECT_URL = 'product_list'
LOGOUT_REDIRECT_URL = 'product_list'
LOGIN_URL = 'login'

# Store branding — change this one line to rename the store everywhere
SITE_NAME = 'Aromallure'

# ── Manual MoMo payment details ─────────────────────────────────────────────
MOMO_NUMBER      = os.environ.get('MOMO_NUMBER', '0505519010')
MOMO_NAME        = os.environ.get('MOMO_NAME', 'NAOMI NANA AKUA ACHEAMPONG')
MOMO_NETWORK     = os.environ.get('MOMO_NETWORK', 'Telecel Cash')

# ── Email via Resend HTTP API ────────────────────────────────────────────────
# emails.py calls Resend's API directly over HTTPS — no SMTP ports needed.
# RESEND_API_KEY and EMAIL_FROM must be set in .env locally and in
# Render's environment variables dashboard for production.
_resend_key = os.environ.get('RESEND_API_KEY', '')
DEFAULT_FROM_EMAIL = os.environ.get(
    'EMAIL_FROM',
    f'{SITE_NAME} <hello@aromallure.store>'
) if _resend_key else f'{SITE_NAME} <noreply@aromallure.store>'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# ── Production security settings ────────────────────────────────────────────
# These are only applied when DEBUG=False (i.e. on Render, not locally).
if not DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        'https://*.onrender.com',
        'https://aromallure.store',
        'https://www.aromallure.store',
    ]
    SESSION_COOKIE_SECURE          = True
    CSRF_COOKIE_SECURE             = True
    SECURE_HSTS_SECONDS            = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD            = True
    # Render terminates HTTPS at the load balancer — this tells Django
    # to trust the X-Forwarded-Proto header so it knows requests are HTTPS.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Do NOT set SECURE_SSL_REDIRECT=True behind Render — Render handles
    # the HTTP→HTTPS redirect itself, and enabling this causes redirect loops.
